Split Elastic5_6_7 for logstashCollector-1.0, modify templates for EL…
WASdev/sample.logstash.collector pull request #16
Opened 2019-09-18 15:26 UTC by ellen-lau

…K6,7 support

For the logstashCollector-1.0 directory: Splits the Elastic5_6_7 directory into its 5, 6, and 7 version counterparts to fix changing template formats in ELK6 and ELK7.

2019-09-18 20:35 UTC, ellen-lau commented
Will continue to test by looking at the dashboards.

2019-09-24 16:00 UTC, donbourne requested changes
- on second though, I think we should get rid of the 17.0.0.1+ files that are for Elastic6/7 since we haven't tested those and since we know they won't work without modifications akin to those for 18.0.0.3+
- should also remove the logstashCollector-1.0/Elastic5_6_7 directory

2019-09-25 17:27 UTC, donbourne approved these changes

2019-09-25 18:54 UTC, donbourne approved these changes

2019-09-25 19:45 UTC, merged